---
title: "Week One Blog"
author: "Gavin Fisher"
date: "2023-05-23"
category: "Week One"
---

# I'm currently hungry.

This is not a heading
```{r, message=TRUE}
print('Hello')
```

```{r, eval=FALSE}
print('Goodbye')
```

```{r, include=False}
#I don't want this to come out in the render
```

```{r, warning=FALSE, message=FALSE}
library(dplyr)
```

```{r}
install.packages(c("tidycensus", "tidyverse"))

install.packages(c("mapview", "plotly", "ggiraph", 
                   "survey", "srvyr"))

library(tidycensus)
library(tidyverse)
library(dplyr)
library(tigris)
library(sf)
options(tigris_use_cache = TRUE)

###
DM_IA_tracts <- map_dfr(c("IA"), ~{
  tracts(.x, cb = TRUE, year = 2021)
}) %>%
  st_transform(8528)  

DM_metro <- core_based_statistical_areas(cb = TRUE, year = 2021) %>%
  filter(str_detect(NAME, "Des Moines")) %>%
  st_transform(8528)

ggplot() + 
  geom_sf(data = DM_IA_tracts, fill = "white", color = "grey") + 
  geom_sf(data = DM_metro, fill = NA, color = "red") + 
  theme_void()
###

###
get_dm_data <- function(state, place) {
  tracts_data <- tracts(state, cb = TRUE, year = 2021) %>%
    filter(NAME == place) %>%
    st_transform(8528)
  
  return(tracts_data)
}

dm_tracts <- get_dm_data("IA", "Des Moines") %>%
  select(GEOID)

acs_data <- get_acs(geography = "tract",
                    variables = c("B01003_001","P1"),
                    state = "IA",
                    tract = dm_tracts$GEOID,
                    survey = "acs5",
                    year = 2021)

dm_data <- left_join(dm_tracts, acs_data, by = "GEOID")
###

#select one county
story_county <- get_acs(
  geography = 'county',
  state = 'IA',
  county = 'Story',
  variables = "B08511_034",
  year = 2021,
  survey = 'acs1' #<<
)

#all counties
county_list <- c('Story', 'Grundy', 'Chickasaw', 'Buchanan')
all_counties <- get_acs(
  geography = 'county',
  state = 'IA',
  county = county_list,
  variables = c("B01003_001", "DPO2_0068P"),
  year = 2021,
  survey = 'acs5' #<<
)


#iowa pumas
library(tigris)
library(mapview)
options(tigris_use_cache = TRUE)
ia_pumas <- pumas(state = "IA", cb = TRUE, year = 2019)
ia_puma_map <- mapview(ia_pumas)
```

