project:
  type: website

website:
  title: "Gavin_DSPG_Blog"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/gavin-fisher-0b3088238/
      - icon: github
        href: https://github.com/Gavinfishy
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

